import javax.swing.*;
import java.awt.*;

public class Form {
    private JPanel mainPanel;
    private JPanel listaCoziPanel;
    private JPanel coadaClientiPanel;
    private JLabel timerLabel;
    private JLabel secundeLabel;
    private JPanel timerPanel;

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 25));
        listaCoziPanel = new JPanel();
        listaCoziPanel.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 25));
        listaCoziPanel.setBackground(new Color(-2252579));
        listaCoziPanel.setPreferredSize(new Dimension(1300, 350));
        mainPanel.add(listaCoziPanel);
        timerPanel = new JPanel();
        timerPanel.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        timerPanel.setBackground(new Color(-7398179));
        listaCoziPanel.add(timerPanel);
        timerLabel = new JLabel();
        timerLabel.setText("TIMER");
        timerPanel.add(timerLabel);
        secundeLabel = new JLabel();
        secundeLabel.setText("Label");
        timerPanel.add(secundeLabel);
        coadaClientiPanel = new JPanel();
        coadaClientiPanel.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        coadaClientiPanel.setBackground(new Color(-4882724));
        coadaClientiPanel.setPreferredSize(new Dimension(1300, 350));
        mainPanel.add(coadaClientiPanel);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }

}
